/**
 * MadnessLab Mock Data — 2026 NCAA Tournament
 *
 * All stats are mock/estimated data for demonstration purposes.
 * Labeled clearly: USE_MOCK_DATA=true
 * To use real data, implement the providers in lib/dataProviders/ and set USE_MOCK_DATA=false
 */

export interface MockTeam {
  id: string
  name: string
  slug: string
  abbreviation: string
  conference: string
  programTier: 'blueblood' | 'power' | 'mid-major' | 'low-major'
  primaryColor: string
  seed: number
  region: 'South' | 'East' | 'West' | 'Midwest'
  isFirstFour: boolean
  stats: {
    adjOE: number
    adjDE: number
    adjEM: number
    tempo: number
    threePointRate: number
    threePointPct: number
    efgPct: number
    ftRate: number
    ftPct: number
    turnoverRate: number
    turnoverForcedRate: number
    offReboundRate: number
    defReboundRate: number
    sosRank: number
    luckFactor: number
    kenpomRank: number
  }
  recentForm: {
    last5wins: number
    last10wins: number
    streakType: 'W' | 'L'
    streakLength: number
    avgMarginLast5: number
  }
  winsTotal?: number
  lossesTotal?: number
  titleProfileScore: number
  upsetVulnerability: number
  espnId?: number
  keyPlayers?: {
    name: string
    position: 'G' | 'F' | 'C'
    ppg: number
    rpg: number
    apg: number
    year: 'Fr' | 'So' | 'Jr' | 'Sr' | 'Gr'
  }[]
}

// ─── SOUTH REGION ─────────────────────────────────────────────────────────────

const SOUTH_TEAMS: MockTeam[] = [
  {
    id: 'auburn',
    name: 'Auburn',
    slug: 'auburn',
    abbreviation: 'AUB',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#0C2340',
    seed: 1,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 121.4, adjDE: 89.2, adjEM: 32.2, tempo: 71.8, threePointRate: 0.38, threePointPct: 0.371, efgPct: 0.565, ftRate: 0.34, ftPct: 0.745, turnoverRate: 16.2, turnoverForcedRate: 22.1, offReboundRate: 32.1, defReboundRate: 74.8, sosRank: 8, luckFactor: 0.021, kenpomRank: 2 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 7, avgMarginLast5: 14.2 },
    titleProfileScore: 88,
    upsetVulnerability: 18,
    keyPlayers: [
      { name: 'Johni Broome', position: 'C', ppg: 17.8, rpg: 10.2, apg: 2.4, year: 'Sr' },
      { name: 'Tre Donaldson', position: 'G', ppg: 13.4, rpg: 3.8, apg: 4.6, year: 'Jr' },
      { name: 'Dylan Cardwell', position: 'C', ppg: 8.2, rpg: 6.8, apg: 1.2, year: 'Jr' },
    ],
  },
  {
    id: 'michigan-state',
    name: 'Michigan State',
    slug: 'michigan-state',
    abbreviation: 'MSU',
    conference: 'Big Ten',
    programTier: 'blueblood',
    primaryColor: '#18453B',
    seed: 2,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 118.2, adjDE: 91.4, adjEM: 26.8, tempo: 68.4, threePointRate: 0.34, threePointPct: 0.356, efgPct: 0.548, ftRate: 0.36, ftPct: 0.718, turnoverRate: 15.8, turnoverForcedRate: 18.4, offReboundRate: 30.2, defReboundRate: 76.1, sosRank: 12, luckFactor: 0.042, kenpomRank: 8 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 3, avgMarginLast5: 8.4 },
    titleProfileScore: 74,
    upsetVulnerability: 28,
  },
  {
    id: 'iowa-state',
    name: 'Iowa State',
    slug: 'iowa-state',
    abbreviation: 'ISU',
    conference: 'Big 12',
    programTier: 'power',
    primaryColor: '#C8102E',
    seed: 3,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 116.8, adjDE: 92.1, adjEM: 24.7, tempo: 66.2, threePointRate: 0.42, threePointPct: 0.378, efgPct: 0.551, ftRate: 0.30, ftPct: 0.762, turnoverRate: 14.1, turnoverForcedRate: 20.2, offReboundRate: 27.8, defReboundRate: 75.4, sosRank: 15, luckFactor: -0.012, kenpomRank: 14 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 9.8 },
    titleProfileScore: 70,
    upsetVulnerability: 32,
  },
  {
    id: 'texas-am',
    name: 'Texas A&M',
    slug: 'texas-am',
    abbreviation: 'TAMU',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#500000',
    seed: 4,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 114.2, adjDE: 93.8, adjEM: 20.4, tempo: 64.8, threePointRate: 0.31, threePointPct: 0.342, efgPct: 0.534, ftRate: 0.40, ftPct: 0.694, turnoverRate: 15.2, turnoverForcedRate: 16.8, offReboundRate: 34.2, defReboundRate: 73.1, sosRank: 18, luckFactor: 0.008, kenpomRank: 22 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 5.6 },
    titleProfileScore: 62,
    upsetVulnerability: 38,
  },
  {
    id: 'michigan',
    name: 'Michigan',
    slug: 'michigan',
    abbreviation: 'MICH',
    conference: 'Big Ten',
    programTier: 'blueblood',
    primaryColor: '#00274C',
    seed: 5,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 113.8, adjDE: 94.2, adjEM: 19.6, tempo: 67.8, threePointRate: 0.37, threePointPct: 0.365, efgPct: 0.541, ftRate: 0.32, ftPct: 0.748, turnoverRate: 14.8, turnoverForcedRate: 17.4, offReboundRate: 28.4, defReboundRate: 72.8, sosRank: 20, luckFactor: 0.054, kenpomRank: 26 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 4.2 },
    titleProfileScore: 55,
    upsetVulnerability: 44,
  },
  {
    id: 'ole-miss',
    name: 'Ole Miss',
    slug: 'ole-miss',
    abbreviation: 'MISS',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#CE1126',
    seed: 6,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 112.4, adjDE: 95.8, adjEM: 16.6, tempo: 70.2, threePointRate: 0.44, threePointPct: 0.352, efgPct: 0.528, ftRate: 0.28, ftPct: 0.738, turnoverRate: 17.4, turnoverForcedRate: 18.8, offReboundRate: 26.4, defReboundRate: 71.2, sosRank: 24, luckFactor: 0.031, kenpomRank: 34 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 6.8 },
    titleProfileScore: 48,
    upsetVulnerability: 50,
  },
  {
    id: 'marquette',
    name: 'Marquette',
    slug: 'marquette',
    abbreviation: 'MU',
    conference: 'Big East',
    programTier: 'power',
    primaryColor: '#003087',
    seed: 7,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 118.2, adjDE: 98.4, adjEM: 19.8, tempo: 72.4, threePointRate: 0.40, threePointPct: 0.374, efgPct: 0.554, ftRate: 0.31, ftPct: 0.752, turnoverRate: 13.8, turnoverForcedRate: 19.2, offReboundRate: 29.1, defReboundRate: 73.4, sosRank: 16, luckFactor: -0.024, kenpomRank: 28 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 7.4 },
    titleProfileScore: 52,
    upsetVulnerability: 46,
  },
  {
    id: 'louisville',
    name: 'Louisville',
    slug: 'louisville',
    abbreviation: 'LOU',
    conference: 'ACC',
    programTier: 'blueblood',
    primaryColor: '#AD0000',
    seed: 8,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 111.8, adjDE: 97.4, adjEM: 14.4, tempo: 69.8, threePointRate: 0.36, threePointPct: 0.348, efgPct: 0.524, ftRate: 0.38, ftPct: 0.712, turnoverRate: 16.8, turnoverForcedRate: 17.6, offReboundRate: 31.2, defReboundRate: 70.8, sosRank: 28, luckFactor: 0.018, kenpomRank: 42 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 2, avgMarginLast5: 3.8 },
    titleProfileScore: 44,
    upsetVulnerability: 54,
  },
  {
    id: 'creighton',
    name: 'Creighton',
    slug: 'creighton',
    abbreviation: 'CREI',
    conference: 'Big East',
    programTier: 'power',
    primaryColor: '#005CA9',
    seed: 9,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 117.4, adjDE: 100.2, adjEM: 17.2, tempo: 73.1, threePointRate: 0.46, threePointPct: 0.381, efgPct: 0.558, ftRate: 0.27, ftPct: 0.771, turnoverRate: 13.2, turnoverForcedRate: 16.4, offReboundRate: 24.8, defReboundRate: 69.4, sosRank: 32, luckFactor: 0.062, kenpomRank: 38 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 5, avgMarginLast5: 11.2 },
    titleProfileScore: 46,
    upsetVulnerability: 58,
  },
  {
    id: 'new-mexico',
    name: 'New Mexico',
    slug: 'new-mexico',
    abbreviation: 'UNM',
    conference: 'Mountain West',
    programTier: 'mid-major',
    primaryColor: '#BA0C2F',
    seed: 10,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 115.2, adjDE: 101.8, adjEM: 13.4, tempo: 71.4, threePointRate: 0.39, threePointPct: 0.362, efgPct: 0.536, ftRate: 0.33, ftPct: 0.728, turnoverRate: 15.6, turnoverForcedRate: 17.8, offReboundRate: 33.8, defReboundRate: 71.8, sosRank: 68, luckFactor: 0.038, kenpomRank: 56 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 9.4 },
    titleProfileScore: 38,
    upsetVulnerability: 62,
  },
  {
    id: 'uc-san-diego',
    name: 'UC San Diego',
    slug: 'uc-san-diego',
    abbreviation: 'UCSD',
    conference: 'Big West',
    programTier: 'mid-major',
    primaryColor: '#182B49',
    seed: 12,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 113.8, adjDE: 103.2, adjEM: 10.6, tempo: 68.8, threePointRate: 0.41, threePointPct: 0.369, efgPct: 0.531, ftRate: 0.29, ftPct: 0.754, turnoverRate: 14.4, turnoverForcedRate: 15.8, offReboundRate: 27.2, defReboundRate: 70.4, sosRank: 124, luckFactor: 0.014, kenpomRank: 82 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 8, avgMarginLast5: 13.6 },
    titleProfileScore: 28,
    upsetVulnerability: 72,
  },
  {
    id: 'yale',
    name: 'Yale',
    slug: 'yale',
    abbreviation: 'YALE',
    conference: 'Ivy League',
    programTier: 'mid-major',
    primaryColor: '#00356B',
    seed: 13,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 112.4, adjDE: 104.8, adjEM: 7.6, tempo: 65.8, threePointRate: 0.43, threePointPct: 0.374, efgPct: 0.527, ftRate: 0.26, ftPct: 0.778, turnoverRate: 13.6, turnoverForcedRate: 14.2, offReboundRate: 24.4, defReboundRate: 68.8, sosRank: 188, luckFactor: -0.008, kenpomRank: 118 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 6, avgMarginLast5: 10.2 },
    titleProfileScore: 22,
    upsetVulnerability: 78,
  },
  {
    id: 'lipscomb',
    name: 'Lipscomb',
    slug: 'lipscomb',
    abbreviation: 'LIP',
    conference: 'ASUN',
    programTier: 'mid-major',
    primaryColor: '#4B2E84',
    seed: 14,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 110.8, adjDE: 106.4, adjEM: 4.4, tempo: 72.8, threePointRate: 0.45, threePointPct: 0.358, efgPct: 0.516, ftRate: 0.31, ftPct: 0.744, turnoverRate: 16.8, turnoverForcedRate: 14.8, offReboundRate: 28.8, defReboundRate: 67.4, sosRank: 224, luckFactor: 0.052, kenpomRank: 168 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 7.8 },
    titleProfileScore: 14,
    upsetVulnerability: 84,
  },
  {
    id: 'bryant',
    name: 'Bryant',
    slug: 'bryant',
    abbreviation: 'BRY',
    conference: 'America East',
    programTier: 'low-major',
    primaryColor: '#231F20',
    seed: 15,
    region: 'South',
    isFirstFour: false,
    stats: { adjOE: 108.2, adjDE: 108.8, adjEM: -0.6, tempo: 74.2, threePointRate: 0.48, threePointPct: 0.344, efgPct: 0.502, ftRate: 0.28, ftPct: 0.726, turnoverRate: 17.8, turnoverForcedRate: 13.4, offReboundRate: 30.4, defReboundRate: 65.8, sosRank: 298, luckFactor: 0.074, kenpomRank: 248 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 4, avgMarginLast5: 6.4 },
    titleProfileScore: 6,
    upsetVulnerability: 92,
  },
  // First Four — Drake/NC State for 11, Prairie View/Lehigh for 16
  {
    id: 'drake',
    name: 'Drake',
    slug: 'drake',
    abbreviation: 'DRAK',
    conference: 'Missouri Valley',
    programTier: 'mid-major',
    primaryColor: '#004B8D',
    seed: 11,
    region: 'South',
    isFirstFour: true,
    stats: { adjOE: 114.2, adjDE: 102.4, adjEM: 11.8, tempo: 67.4, threePointRate: 0.40, threePointPct: 0.370, efgPct: 0.533, ftRate: 0.30, ftPct: 0.748, turnoverRate: 14.2, turnoverForcedRate: 16.4, offReboundRate: 26.8, defReboundRate: 70.2, sosRank: 88, luckFactor: 0.028, kenpomRank: 72 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 5.8 },
    titleProfileScore: 30,
    upsetVulnerability: 70,
  },
  {
    id: 'nc-state',
    name: 'NC State',
    slug: 'nc-state',
    abbreviation: 'NCST',
    conference: 'ACC',
    programTier: 'power',
    primaryColor: '#CC0000',
    seed: 11,
    region: 'South',
    isFirstFour: true,
    stats: { adjOE: 113.2, adjDE: 103.8, adjEM: 9.4, tempo: 70.2, threePointRate: 0.37, threePointPct: 0.352, efgPct: 0.521, ftRate: 0.32, ftPct: 0.736, turnoverRate: 15.4, turnoverForcedRate: 16.8, offReboundRate: 29.2, defReboundRate: 69.8, sosRank: 64, luckFactor: 0.012, kenpomRank: 88 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 4.2 },
    titleProfileScore: 26,
    upsetVulnerability: 74,
    espnId: 152,
  },
  {
    id: 'prairie-view-am',
    name: 'Prairie View A&M',
    slug: 'prairie-view-am',
    abbreviation: 'PVAM',
    conference: 'SWAC',
    programTier: 'low-major',
    primaryColor: '#4B1979',
    seed: 16,
    region: 'South',
    isFirstFour: true,
    stats: { adjOE: 101.5, adjDE: 111.4, adjEM: -9.9, tempo: 68.0, threePointRate: 0.35, threePointPct: 0.332, efgPct: 0.504, ftRate: 0.32, ftPct: 0.720, turnoverRate: 17.0, turnoverForcedRate: 19.0, offReboundRate: 28.0, defReboundRate: 71.0, sosRank: 300, luckFactor: 0.000, kenpomRank: 320 },
    recentForm: { last5wins: 1, last10wins: 3, streakType: 'W', streakLength: 1, avgMarginLast5: -7.3 },
    titleProfileScore: 2,
    upsetVulnerability: 95,
    espnId: 2480,
  },
  {
    id: 'lehigh',
    name: 'Lehigh',
    slug: 'lehigh',
    abbreviation: 'LEH',
    conference: 'Patriot',
    programTier: 'low-major',
    primaryColor: '#653819',
    seed: 16,
    region: 'South',
    isFirstFour: true,
    stats: { adjOE: 102.6, adjDE: 112.8, adjEM: -10.2, tempo: 66.4, threePointRate: 0.36, threePointPct: 0.338, efgPct: 0.498, ftRate: 0.30, ftPct: 0.716, turnoverRate: 16.4, turnoverForcedRate: 18.2, offReboundRate: 26.8, defReboundRate: 69.4, sosRank: 280, luckFactor: 0.000, kenpomRank: 310 },
    recentForm: { last5wins: 1, last10wins: 3, streakType: 'L', streakLength: 2, avgMarginLast5: -8.1 },
    titleProfileScore: 2,
    upsetVulnerability: 95,
    espnId: 122,
  },
]

// ─── EAST REGION ──────────────────────────────────────────────────────────────

const EAST_TEAMS: MockTeam[] = [
  {
    id: 'duke',
    name: 'Duke',
    slug: 'duke',
    abbreviation: 'DUKE',
    conference: 'ACC',
    programTier: 'blueblood',
    primaryColor: '#003087',
    seed: 1,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 122.8, adjDE: 88.4, adjEM: 34.4, tempo: 73.4, threePointRate: 0.37, threePointPct: 0.381, efgPct: 0.574, ftRate: 0.38, ftPct: 0.762, turnoverRate: 14.8, turnoverForcedRate: 21.4, offReboundRate: 31.8, defReboundRate: 76.4, sosRank: 6, luckFactor: 0.014, kenpomRank: 1 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 8, avgMarginLast5: 16.4 },
    titleProfileScore: 92,
    upsetVulnerability: 14,
  },
  {
    id: 'alabama',
    name: 'Alabama',
    slug: 'alabama',
    abbreviation: 'ALA',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#9E1B32',
    seed: 2,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 120.4, adjDE: 91.8, adjEM: 28.6, tempo: 76.2, threePointRate: 0.46, threePointPct: 0.374, efgPct: 0.562, ftRate: 0.32, ftPct: 0.724, turnoverRate: 16.8, turnoverForcedRate: 22.8, offReboundRate: 28.4, defReboundRate: 73.8, sosRank: 10, luckFactor: 0.008, kenpomRank: 4 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 11.8 },
    titleProfileScore: 80,
    upsetVulnerability: 26,
  },
  {
    id: 'wisconsin',
    name: 'Wisconsin',
    slug: 'wisconsin',
    abbreviation: 'WIS',
    conference: 'Big Ten',
    programTier: 'power',
    primaryColor: '#C5050C',
    seed: 3,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 115.8, adjDE: 90.2, adjEM: 25.6, tempo: 61.4, threePointRate: 0.35, threePointPct: 0.360, efgPct: 0.546, ftRate: 0.35, ftPct: 0.772, turnoverRate: 12.4, turnoverForcedRate: 16.2, offReboundRate: 26.8, defReboundRate: 77.4, sosRank: 22, luckFactor: -0.018, kenpomRank: 12 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 6, avgMarginLast5: 12.4 },
    titleProfileScore: 76,
    upsetVulnerability: 24,
  },
  {
    id: 'arizona',
    name: 'Arizona',
    slug: 'arizona',
    abbreviation: 'ARIZ',
    conference: 'Big 12',
    programTier: 'blueblood',
    primaryColor: '#003366',
    seed: 4,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 116.4, adjDE: 94.8, adjEM: 21.6, tempo: 70.8, threePointRate: 0.33, threePointPct: 0.346, efgPct: 0.540, ftRate: 0.42, ftPct: 0.728, turnoverRate: 15.4, turnoverForcedRate: 17.4, offReboundRate: 33.4, defReboundRate: 74.2, sosRank: 14, luckFactor: 0.044, kenpomRank: 18 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'L', streakLength: 1, avgMarginLast5: 4.8 },
    titleProfileScore: 64,
    upsetVulnerability: 36,
  },
  {
    id: 'oregon',
    name: 'Oregon',
    slug: 'oregon',
    abbreviation: 'ORE',
    conference: 'Big Ten',
    programTier: 'power',
    primaryColor: '#154733',
    seed: 5,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 114.8, adjDE: 95.4, adjEM: 19.4, tempo: 72.4, threePointRate: 0.41, threePointPct: 0.368, efgPct: 0.543, ftRate: 0.33, ftPct: 0.746, turnoverRate: 15.8, turnoverForcedRate: 18.4, offReboundRate: 29.8, defReboundRate: 72.4, sosRank: 26, luckFactor: -0.006, kenpomRank: 30 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 4.2 },
    titleProfileScore: 54,
    upsetVulnerability: 46,
  },
  {
    id: 'byu',
    name: 'BYU',
    slug: 'byu',
    abbreviation: 'BYU',
    conference: 'Big 12',
    programTier: 'power',
    primaryColor: '#002E5D',
    seed: 6,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 117.8, adjDE: 99.2, adjEM: 18.6, tempo: 69.8, threePointRate: 0.43, threePointPct: 0.375, efgPct: 0.553, ftRate: 0.29, ftPct: 0.766, turnoverRate: 13.4, turnoverForcedRate: 16.8, offReboundRate: 27.4, defReboundRate: 71.8, sosRank: 30, luckFactor: 0.022, kenpomRank: 36 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 8.8 },
    titleProfileScore: 50,
    upsetVulnerability: 52,
  },
  {
    id: 'saint-marys',
    name: "Saint Mary's",
    slug: 'saint-marys',
    abbreviation: 'SMC',
    conference: 'WCC',
    programTier: 'mid-major',
    primaryColor: '#0E1C40',
    seed: 7,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 115.4, adjDE: 98.8, adjEM: 16.6, tempo: 63.8, threePointRate: 0.36, threePointPct: 0.362, efgPct: 0.543, ftRate: 0.32, ftPct: 0.776, turnoverRate: 12.8, turnoverForcedRate: 15.4, offReboundRate: 26.2, defReboundRate: 73.8, sosRank: 48, luckFactor: -0.014, kenpomRank: 44 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 5, avgMarginLast5: 10.4 },
    titleProfileScore: 48,
    upsetVulnerability: 54,
  },
  {
    id: 'mississippi-state',
    name: 'Mississippi State',
    slug: 'mississippi-state',
    abbreviation: 'MSST',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#660000',
    seed: 8,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 110.4, adjDE: 96.8, adjEM: 13.6, tempo: 68.2, threePointRate: 0.32, threePointPct: 0.334, efgPct: 0.518, ftRate: 0.41, ftPct: 0.706, turnoverRate: 17.4, turnoverForcedRate: 18.2, offReboundRate: 33.8, defReboundRate: 72.4, sosRank: 34, luckFactor: 0.036, kenpomRank: 54 },
    recentForm: { last5wins: 2, last10wins: 5, streakType: 'L', streakLength: 2, avgMarginLast5: -2.4 },
    titleProfileScore: 40,
    upsetVulnerability: 60,
  },
  {
    id: 'baylor',
    name: 'Baylor',
    slug: 'baylor',
    abbreviation: 'BAY',
    conference: 'Big 12',
    programTier: 'blueblood',
    primaryColor: '#154734',
    seed: 9,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 116.8, adjDE: 101.4, adjEM: 15.4, tempo: 71.8, threePointRate: 0.38, threePointPct: 0.368, efgPct: 0.547, ftRate: 0.34, ftPct: 0.742, turnoverRate: 14.8, turnoverForcedRate: 19.4, offReboundRate: 30.4, defReboundRate: 71.8, sosRank: 22, luckFactor: -0.028, kenpomRank: 48 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 3.8 },
    titleProfileScore: 42,
    upsetVulnerability: 56,
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt',
    slug: 'vanderbilt',
    abbreviation: 'VAN',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#866D4B',
    seed: 10,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 114.4, adjDE: 102.8, adjEM: 11.6, tempo: 69.4, threePointRate: 0.40, threePointPct: 0.361, efgPct: 0.530, ftRate: 0.31, ftPct: 0.752, turnoverRate: 15.2, turnoverForcedRate: 16.8, offReboundRate: 27.8, defReboundRate: 70.8, sosRank: 42, luckFactor: 0.018, kenpomRank: 62 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 6.2 },
    titleProfileScore: 35,
    upsetVulnerability: 64,
  },
  {
    id: 'vcu',
    name: 'VCU',
    slug: 'vcu',
    abbreviation: 'VCU',
    conference: 'Atlantic 10',
    programTier: 'mid-major',
    primaryColor: '#FFB300',
    seed: 11,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 112.8, adjDE: 100.4, adjEM: 12.4, tempo: 75.4, threePointRate: 0.36, threePointPct: 0.344, efgPct: 0.522, ftRate: 0.38, ftPct: 0.714, turnoverRate: 18.4, turnoverForcedRate: 24.8, offReboundRate: 32.4, defReboundRate: 71.2, sosRank: 72, luckFactor: 0.034, kenpomRank: 68 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 8.4 },
    titleProfileScore: 32,
    upsetVulnerability: 68,
  },
  {
    id: 'liberty',
    name: 'Liberty',
    slug: 'liberty',
    abbreviation: 'LIB',
    conference: 'ASUN',
    programTier: 'mid-major',
    primaryColor: '#002868',
    seed: 12,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 113.4, adjDE: 103.8, adjEM: 9.6, tempo: 68.4, threePointRate: 0.44, threePointPct: 0.366, efgPct: 0.528, ftRate: 0.29, ftPct: 0.756, turnoverRate: 14.8, turnoverForcedRate: 15.6, offReboundRate: 28.4, defReboundRate: 69.8, sosRank: 108, luckFactor: 0.024, kenpomRank: 86 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 7, avgMarginLast5: 12.8 },
    titleProfileScore: 25,
    upsetVulnerability: 74,
  },
  {
    id: 'akron',
    name: 'Akron',
    slug: 'akron',
    abbreviation: 'AKR',
    conference: 'MAC',
    programTier: 'mid-major',
    primaryColor: '#00285E',
    seed: 13,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 111.4, adjDE: 105.2, adjEM: 6.2, tempo: 67.8, threePointRate: 0.42, threePointPct: 0.358, efgPct: 0.521, ftRate: 0.28, ftPct: 0.742, turnoverRate: 14.2, turnoverForcedRate: 14.8, offReboundRate: 25.8, defReboundRate: 68.4, sosRank: 182, luckFactor: 0.012, kenpomRank: 128 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 5, avgMarginLast5: 8.6 },
    titleProfileScore: 18,
    upsetVulnerability: 80,
  },
  {
    id: 'montana',
    name: 'Montana',
    slug: 'montana',
    abbreviation: 'MONT',
    conference: 'Big Sky',
    programTier: 'low-major',
    primaryColor: '#660000',
    seed: 14,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 109.8, adjDE: 107.2, adjEM: 2.6, tempo: 70.4, threePointRate: 0.43, threePointPct: 0.352, efgPct: 0.512, ftRate: 0.30, ftPct: 0.748, turnoverRate: 15.8, turnoverForcedRate: 14.4, offReboundRate: 28.2, defReboundRate: 67.2, sosRank: 248, luckFactor: 0.048, kenpomRank: 178 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 7.4 },
    titleProfileScore: 12,
    upsetVulnerability: 86,
  },
  {
    id: 'robert-morris',
    name: 'Robert Morris',
    slug: 'robert-morris',
    abbreviation: 'RMU',
    conference: 'Horizon',
    programTier: 'low-major',
    primaryColor: '#14234B',
    seed: 15,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 107.4, adjDE: 109.4, adjEM: -2.0, tempo: 72.8, threePointRate: 0.45, threePointPct: 0.341, efgPct: 0.498, ftRate: 0.30, ftPct: 0.724, turnoverRate: 18.2, turnoverForcedRate: 13.8, offReboundRate: 30.8, defReboundRate: 65.4, sosRank: 312, luckFactor: 0.062, kenpomRank: 262 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 4, avgMarginLast5: 5.8 },
    titleProfileScore: 4,
    upsetVulnerability: 94,
  },
  {
    id: 'siena',
    name: 'Siena',
    slug: 'siena',
    abbreviation: 'SIE',
    conference: 'MAAC',
    programTier: 'low-major',
    primaryColor: '#006747',
    seed: 16,
    region: 'East',
    isFirstFour: false,
    stats: { adjOE: 107.2, adjDE: 108.9, adjEM: -1.7, tempo: 63.8, threePointRate: 0.34, threePointPct: 0.304, efgPct: 0.486, ftRate: 0.32, ftPct: 0.720, turnoverRate: 16.2, turnoverForcedRate: 19.0, offReboundRate: 34.4, defReboundRate: 79.9, sosRank: 290, luckFactor: 0.000, kenpomRank: 295 },
    recentForm: { last5wins: 2, last10wins: 5, streakType: 'W', streakLength: 1, avgMarginLast5: -1.4 },
    titleProfileScore: 3,
    upsetVulnerability: 96,
    espnId: 2561,
  },
]

// ─── WEST REGION ──────────────────────────────────────────────────────────────

const WEST_TEAMS: MockTeam[] = [
  {
    id: 'florida',
    name: 'Florida',
    slug: 'florida',
    abbreviation: 'FLA',
    conference: 'SEC',
    programTier: 'blueblood',
    primaryColor: '#0021A5',
    seed: 1,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 119.8, adjDE: 87.8, adjEM: 32.0, tempo: 72.4, threePointRate: 0.36, threePointPct: 0.372, efgPct: 0.562, ftRate: 0.37, ftPct: 0.748, turnoverRate: 15.4, turnoverForcedRate: 20.8, offReboundRate: 30.8, defReboundRate: 75.8, sosRank: 7, luckFactor: 0.028, kenpomRank: 3 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 9, avgMarginLast5: 15.4 },
    titleProfileScore: 90,
    upsetVulnerability: 16,
  },
  {
    id: 'st-johns',
    name: "St. John's",
    slug: 'st-johns',
    abbreviation: 'SJU',
    conference: 'Big East',
    programTier: 'power',
    primaryColor: '#9E1B32',
    seed: 2,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 119.4, adjDE: 92.8, adjEM: 26.6, tempo: 74.8, threePointRate: 0.38, threePointPct: 0.368, efgPct: 0.556, ftRate: 0.36, ftPct: 0.732, turnoverRate: 16.4, turnoverForcedRate: 21.4, offReboundRate: 31.4, defReboundRate: 74.4, sosRank: 11, luckFactor: -0.004, kenpomRank: 6 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 3, avgMarginLast5: 10.8 },
    titleProfileScore: 76,
    upsetVulnerability: 24,
  },
  {
    id: 'texas-tech',
    name: 'Texas Tech',
    slug: 'texas-tech',
    abbreviation: 'TTU',
    conference: 'Big 12',
    programTier: 'power',
    primaryColor: '#CC0000',
    seed: 3,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 114.8, adjDE: 89.8, adjEM: 25.0, tempo: 65.4, threePointRate: 0.33, threePointPct: 0.351, efgPct: 0.541, ftRate: 0.38, ftPct: 0.714, turnoverRate: 14.8, turnoverForcedRate: 20.4, offReboundRate: 29.8, defReboundRate: 76.8, sosRank: 16, luckFactor: -0.022, kenpomRank: 11 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 10.2 },
    titleProfileScore: 72,
    upsetVulnerability: 28,
  },
  {
    id: 'maryland',
    name: 'Maryland',
    slug: 'maryland',
    abbreviation: 'MD',
    conference: 'Big Ten',
    programTier: 'power',
    primaryColor: '#E03A3E',
    seed: 4,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 115.4, adjDE: 95.4, adjEM: 20.0, tempo: 69.2, threePointRate: 0.37, threePointPct: 0.358, efgPct: 0.538, ftRate: 0.34, ftPct: 0.728, turnoverRate: 15.6, turnoverForcedRate: 17.8, offReboundRate: 31.8, defReboundRate: 73.4, sosRank: 18, luckFactor: 0.016, kenpomRank: 24 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 6.4 },
    titleProfileScore: 60,
    upsetVulnerability: 40,
  },
  {
    id: 'memphis',
    name: 'Memphis',
    slug: 'memphis',
    abbreviation: 'MEM',
    conference: 'American',
    programTier: 'power',
    primaryColor: '#003087',
    seed: 5,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 116.8, adjDE: 97.4, adjEM: 19.4, tempo: 77.8, threePointRate: 0.34, threePointPct: 0.348, efgPct: 0.543, ftRate: 0.44, ftPct: 0.698, turnoverRate: 17.8, turnoverForcedRate: 21.8, offReboundRate: 36.4, defReboundRate: 72.8, sosRank: 28, luckFactor: 0.038, kenpomRank: 28 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 8.4 },
    titleProfileScore: 56,
    upsetVulnerability: 48,
  },
  {
    id: 'missouri',
    name: 'Missouri',
    slug: 'missouri',
    abbreviation: 'MIZ',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#F1B82D',
    seed: 6,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 113.2, adjDE: 96.8, adjEM: 16.4, tempo: 70.8, threePointRate: 0.38, threePointPct: 0.354, efgPct: 0.528, ftRate: 0.36, ftPct: 0.722, turnoverRate: 15.8, turnoverForcedRate: 17.2, offReboundRate: 29.4, defReboundRate: 72.2, sosRank: 26, luckFactor: 0.044, kenpomRank: 38 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 4.8 },
    titleProfileScore: 46,
    upsetVulnerability: 52,
  },
  {
    id: 'kansas',
    name: 'Kansas',
    slug: 'kansas',
    abbreviation: 'KU',
    conference: 'Big 12',
    programTier: 'blueblood',
    primaryColor: '#0051A5',
    seed: 7,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 117.4, adjDE: 99.8, adjEM: 17.6, tempo: 71.4, threePointRate: 0.37, threePointPct: 0.363, efgPct: 0.549, ftRate: 0.33, ftPct: 0.738, turnoverRate: 14.4, turnoverForcedRate: 18.4, offReboundRate: 29.8, defReboundRate: 72.6, sosRank: 14, luckFactor: -0.032, kenpomRank: 32 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'L', streakLength: 1, avgMarginLast5: 2.8 },
    titleProfileScore: 50,
    upsetVulnerability: 54,
  },
  {
    id: 'connecticut',
    name: 'Connecticut',
    slug: 'connecticut',
    abbreviation: 'CONN',
    conference: 'Big East',
    programTier: 'blueblood',
    primaryColor: '#000E2F',
    seed: 8,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 114.4, adjDE: 99.2, adjEM: 15.2, tempo: 69.8, threePointRate: 0.34, threePointPct: 0.354, efgPct: 0.534, ftRate: 0.37, ftPct: 0.742, turnoverRate: 15.2, turnoverForcedRate: 18.8, offReboundRate: 30.8, defReboundRate: 73.8, sosRank: 20, luckFactor: -0.018, kenpomRank: 46 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 2, avgMarginLast5: 3.4 },
    titleProfileScore: 44,
    upsetVulnerability: 58,
  },
  {
    id: 'oklahoma',
    name: 'Oklahoma',
    slug: 'oklahoma',
    abbreviation: 'OU',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#841617',
    seed: 9,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 115.8, adjDE: 101.8, adjEM: 14.0, tempo: 72.8, threePointRate: 0.42, threePointPct: 0.364, efgPct: 0.540, ftRate: 0.30, ftPct: 0.744, turnoverRate: 16.2, turnoverForcedRate: 17.8, offReboundRate: 28.8, defReboundRate: 71.4, sosRank: 38, luckFactor: 0.026, kenpomRank: 52 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 2, avgMarginLast5: 5.2 },
    titleProfileScore: 40,
    upsetVulnerability: 60,
  },
  {
    id: 'arkansas',
    name: 'Arkansas',
    slug: 'arkansas',
    abbreviation: 'ARK',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#9D2235',
    seed: 10,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 113.8, adjDE: 103.2, adjEM: 10.6, tempo: 74.2, threePointRate: 0.36, threePointPct: 0.348, efgPct: 0.526, ftRate: 0.42, ftPct: 0.706, turnoverRate: 17.2, turnoverForcedRate: 20.4, offReboundRate: 35.2, defReboundRate: 72.8, sosRank: 32, luckFactor: 0.054, kenpomRank: 64 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 3.8 },
    titleProfileScore: 36,
    upsetVulnerability: 64,
  },
  {
    id: 'colorado-state',
    name: 'Colorado State',
    slug: 'colorado-state',
    abbreviation: 'CSU',
    conference: 'Mountain West',
    programTier: 'mid-major',
    primaryColor: '#1E4D2B',
    seed: 12,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 114.4, adjDE: 104.2, adjEM: 10.2, tempo: 69.4, threePointRate: 0.40, threePointPct: 0.371, efgPct: 0.530, ftRate: 0.31, ftPct: 0.748, turnoverRate: 14.4, turnoverForcedRate: 15.4, offReboundRate: 28.8, defReboundRate: 70.8, sosRank: 78, luckFactor: 0.016, kenpomRank: 78 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 5, avgMarginLast5: 10.8 },
    titleProfileScore: 28,
    upsetVulnerability: 72,
  },
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    slug: 'grand-canyon',
    abbreviation: 'GCU',
    conference: 'WAC',
    programTier: 'mid-major',
    primaryColor: '#522498',
    seed: 13,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 112.2, adjDE: 105.8, adjEM: 6.4, tempo: 68.2, threePointRate: 0.43, threePointPct: 0.362, efgPct: 0.522, ftRate: 0.28, ftPct: 0.758, turnoverRate: 14.8, turnoverForcedRate: 14.4, offReboundRate: 26.8, defReboundRate: 68.8, sosRank: 198, luckFactor: 0.022, kenpomRank: 132 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 6, avgMarginLast5: 11.4 },
    titleProfileScore: 20,
    upsetVulnerability: 78,
  },
  {
    id: 'high-point',
    name: 'High Point',
    slug: 'high-point',
    abbreviation: 'HPU',
    conference: 'Big South',
    programTier: 'low-major',
    primaryColor: '#522D80',
    seed: 14,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 110.4, adjDE: 107.4, adjEM: 3.0, tempo: 71.8, threePointRate: 0.44, threePointPct: 0.354, efgPct: 0.512, ftRate: 0.29, ftPct: 0.738, turnoverRate: 16.2, turnoverForcedRate: 14.2, offReboundRate: 28.2, defReboundRate: 66.8, sosRank: 258, luckFactor: 0.044, kenpomRank: 184 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 6.8 },
    titleProfileScore: 11,
    upsetVulnerability: 87,
  },
  {
    id: 'wofford',
    name: 'Wofford',
    slug: 'wofford',
    abbreviation: 'WOF',
    conference: 'SoCon',
    programTier: 'low-major',
    primaryColor: '#866D4B',
    seed: 15,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 108.8, adjDE: 109.2, adjEM: -0.4, tempo: 68.4, threePointRate: 0.48, threePointPct: 0.358, efgPct: 0.506, ftRate: 0.27, ftPct: 0.762, turnoverRate: 14.8, turnoverForcedRate: 13.2, offReboundRate: 26.8, defReboundRate: 66.2, sosRank: 302, luckFactor: 0.058, kenpomRank: 252 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 4, avgMarginLast5: 5.4 },
    titleProfileScore: 5,
    upsetVulnerability: 93,
  },
  // First Four — Missouri Valley / 11 seed
  {
    id: 'drake-west',
    name: 'Drake',
    slug: 'drake-west',
    abbreviation: 'DRAK',
    conference: 'Missouri Valley',
    programTier: 'mid-major',
    primaryColor: '#004B8D',
    seed: 11,
    region: 'West',
    isFirstFour: true,
    stats: { adjOE: 113.8, adjDE: 102.8, adjEM: 11.0, tempo: 67.4, threePointRate: 0.40, threePointPct: 0.365, efgPct: 0.528, ftRate: 0.30, ftPct: 0.742, turnoverRate: 14.8, turnoverForcedRate: 16.2, offReboundRate: 26.4, defReboundRate: 70.0, sosRank: 92, luckFactor: 0.018, kenpomRank: 76 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 3.8 },
    titleProfileScore: 28,
    upsetVulnerability: 72,
  },
  {
    id: 'long-island',
    name: 'Long Island',
    slug: 'long-island',
    abbreviation: 'LIU',
    conference: 'NEC',
    programTier: 'low-major',
    primaryColor: '#000000',
    seed: 16,
    region: 'West',
    isFirstFour: false,
    stats: { adjOE: 103.6, adjDE: 109.8, adjEM: -6.1, tempo: 67.5, threePointRate: 0.37, threePointPct: 0.361, efgPct: 0.498, ftRate: 0.32, ftPct: 0.720, turnoverRate: 19.3, turnoverForcedRate: 19.0, offReboundRate: 37.5, defReboundRate: 77.6, sosRank: 310, luckFactor: 0.000, kenpomRank: 315 },
    recentForm: { last5wins: 2, last10wins: 3, streakType: 'W', streakLength: 1, avgMarginLast5: -4.8 },
    titleProfileScore: 2,
    upsetVulnerability: 97,
    espnId: 112358,
  },
]

// ─── MIDWEST REGION ────────────────────────────────────────────────────────────

const MIDWEST_TEAMS: MockTeam[] = [
  {
    id: 'houston',
    name: 'Houston',
    slug: 'houston',
    abbreviation: 'HOU',
    conference: 'Big 12',
    programTier: 'power',
    primaryColor: '#C8102E',
    seed: 1,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 118.4, adjDE: 86.8, adjEM: 31.6, tempo: 64.8, threePointRate: 0.30, threePointPct: 0.344, efgPct: 0.548, ftRate: 0.44, ftPct: 0.704, turnoverRate: 15.8, turnoverForcedRate: 23.4, offReboundRate: 33.4, defReboundRate: 77.8, sosRank: 9, luckFactor: 0.006, kenpomRank: 5 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 6, avgMarginLast5: 13.8 },
    titleProfileScore: 86,
    upsetVulnerability: 20,
  },
  {
    id: 'tennessee',
    name: 'Tennessee',
    slug: 'tennessee',
    abbreviation: 'TENN',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#FF8200',
    seed: 2,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 116.8, adjDE: 89.4, adjEM: 27.4, tempo: 67.8, threePointRate: 0.36, threePointPct: 0.358, efgPct: 0.549, ftRate: 0.38, ftPct: 0.726, turnoverRate: 14.8, turnoverForcedRate: 20.8, offReboundRate: 30.4, defReboundRate: 75.4, sosRank: 13, luckFactor: 0.018, kenpomRank: 7 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 10.4 },
    titleProfileScore: 78,
    upsetVulnerability: 22,
  },
  {
    id: 'kentucky',
    name: 'Kentucky',
    slug: 'kentucky',
    abbreviation: 'UK',
    conference: 'SEC',
    programTier: 'blueblood',
    primaryColor: '#0033A0',
    seed: 3,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 117.8, adjDE: 92.4, adjEM: 25.4, tempo: 71.2, threePointRate: 0.35, threePointPct: 0.355, efgPct: 0.550, ftRate: 0.37, ftPct: 0.732, turnoverRate: 15.2, turnoverForcedRate: 19.4, offReboundRate: 32.8, defReboundRate: 74.8, sosRank: 11, luckFactor: -0.008, kenpomRank: 10 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 3, avgMarginLast5: 9.8 },
    titleProfileScore: 74,
    upsetVulnerability: 26,
  },
  {
    id: 'purdue',
    name: 'Purdue',
    slug: 'purdue',
    abbreviation: 'PUR',
    conference: 'Big Ten',
    programTier: 'power',
    primaryColor: '#CEB888',
    seed: 4,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 119.4, adjDE: 96.4, adjEM: 23.0, tempo: 66.8, threePointRate: 0.36, threePointPct: 0.367, efgPct: 0.554, ftRate: 0.34, ftPct: 0.746, turnoverRate: 13.8, turnoverForcedRate: 17.2, offReboundRate: 29.4, defReboundRate: 74.2, sosRank: 17, luckFactor: -0.014, kenpomRank: 16 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 7.8 },
    titleProfileScore: 68,
    upsetVulnerability: 30,
  },
  {
    id: 'clemson',
    name: 'Clemson',
    slug: 'clemson',
    abbreviation: 'CLEM',
    conference: 'ACC',
    programTier: 'power',
    primaryColor: '#F56600',
    seed: 5,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 115.4, adjDE: 96.8, adjEM: 18.6, tempo: 68.4, threePointRate: 0.38, threePointPct: 0.362, efgPct: 0.542, ftRate: 0.33, ftPct: 0.736, turnoverRate: 14.8, turnoverForcedRate: 18.2, offReboundRate: 29.8, defReboundRate: 72.8, sosRank: 24, luckFactor: 0.028, kenpomRank: 32 },
    recentForm: { last5wins: 3, last10wins: 7, streakType: 'W', streakLength: 2, avgMarginLast5: 6.2 },
    titleProfileScore: 54,
    upsetVulnerability: 46,
  },
  {
    id: 'illinois',
    name: 'Illinois',
    slug: 'illinois',
    abbreviation: 'ILL',
    conference: 'Big Ten',
    programTier: 'power',
    primaryColor: '#13294B',
    seed: 6,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 116.8, adjDE: 99.4, adjEM: 17.4, tempo: 70.8, threePointRate: 0.37, threePointPct: 0.365, efgPct: 0.547, ftRate: 0.32, ftPct: 0.742, turnoverRate: 15.4, turnoverForcedRate: 17.8, offReboundRate: 30.8, defReboundRate: 73.4, sosRank: 20, luckFactor: -0.016, kenpomRank: 36 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 4.4 },
    titleProfileScore: 48,
    upsetVulnerability: 52,
  },
  {
    id: 'ucla',
    name: 'UCLA',
    slug: 'ucla',
    abbreviation: 'UCLA',
    conference: 'Big Ten',
    programTier: 'blueblood',
    primaryColor: '#2D68C4',
    seed: 7,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 116.4, adjDE: 100.2, adjEM: 16.2, tempo: 69.4, threePointRate: 0.35, threePointPct: 0.358, efgPct: 0.543, ftRate: 0.35, ftPct: 0.748, turnoverRate: 14.4, turnoverForcedRate: 17.4, offReboundRate: 28.8, defReboundRate: 73.0, sosRank: 18, luckFactor: -0.022, kenpomRank: 40 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'L', streakLength: 1, avgMarginLast5: 1.8 },
    titleProfileScore: 46,
    upsetVulnerability: 56,
  },
  {
    id: 'gonzaga',
    name: 'Gonzaga',
    slug: 'gonzaga',
    abbreviation: 'GONZ',
    conference: 'WCC',
    programTier: 'power',
    primaryColor: '#002160',
    seed: 8,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 120.4, adjDE: 103.8, adjEM: 16.6, tempo: 74.8, threePointRate: 0.36, threePointPct: 0.368, efgPct: 0.558, ftRate: 0.33, ftPct: 0.762, turnoverRate: 13.4, turnoverForcedRate: 16.8, offReboundRate: 29.4, defReboundRate: 72.4, sosRank: 44, luckFactor: 0.012, kenpomRank: 44 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 8.4 },
    titleProfileScore: 50,
    upsetVulnerability: 54,
  },
  {
    id: 'georgia',
    name: 'Georgia',
    slug: 'georgia',
    abbreviation: 'UGA',
    conference: 'SEC',
    programTier: 'power',
    primaryColor: '#BA0C2F',
    seed: 9,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 114.4, adjDE: 101.8, adjEM: 12.6, tempo: 70.4, threePointRate: 0.38, threePointPct: 0.356, efgPct: 0.528, ftRate: 0.34, ftPct: 0.724, turnoverRate: 16.4, turnoverForcedRate: 17.4, offReboundRate: 30.8, defReboundRate: 71.4, sosRank: 30, luckFactor: 0.042, kenpomRank: 58 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 2, avgMarginLast5: 4.8 },
    titleProfileScore: 38,
    upsetVulnerability: 62,
  },
  {
    id: 'utah-state',
    name: 'Utah State',
    slug: 'utah-state',
    abbreviation: 'USU',
    conference: 'Mountain West',
    programTier: 'mid-major',
    primaryColor: '#00263A',
    seed: 10,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 116.2, adjDE: 103.8, adjEM: 12.4, tempo: 67.2, threePointRate: 0.38, threePointPct: 0.368, efgPct: 0.535, ftRate: 0.32, ftPct: 0.754, turnoverRate: 14.2, turnoverForcedRate: 16.8, offReboundRate: 28.2, defReboundRate: 71.8, sosRank: 58, luckFactor: 0.028, kenpomRank: 60 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 4, avgMarginLast5: 8.8 },
    titleProfileScore: 34,
    upsetVulnerability: 64,
  },
  {
    id: 'xavier',
    name: 'Xavier',
    slug: 'xavier',
    abbreviation: 'XAV',
    conference: 'Big East',
    programTier: 'power',
    primaryColor: '#1D2951',
    seed: 11,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 113.8, adjDE: 102.4, adjEM: 11.4, tempo: 70.8, threePointRate: 0.41, threePointPct: 0.362, efgPct: 0.528, ftRate: 0.30, ftPct: 0.748, turnoverRate: 15.8, turnoverForcedRate: 17.2, offReboundRate: 27.4, defReboundRate: 70.4, sosRank: 36, luckFactor: 0.034, kenpomRank: 70 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 1, avgMarginLast5: 3.4 },
    titleProfileScore: 32,
    upsetVulnerability: 68,
  },
  {
    id: 'mcneese',
    name: 'McNeese',
    slug: 'mcneese',
    abbreviation: 'MCN',
    conference: 'Southland',
    programTier: 'mid-major',
    primaryColor: '#006636',
    seed: 12,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 113.2, adjDE: 104.8, adjEM: 8.4, tempo: 71.8, threePointRate: 0.42, threePointPct: 0.368, efgPct: 0.527, ftRate: 0.30, ftPct: 0.746, turnoverRate: 15.2, turnoverForcedRate: 15.8, offReboundRate: 27.8, defReboundRate: 69.8, sosRank: 142, luckFactor: 0.018, kenpomRank: 94 },
    recentForm: { last5wins: 5, last10wins: 9, streakType: 'W', streakLength: 8, avgMarginLast5: 13.2 },
    titleProfileScore: 22,
    upsetVulnerability: 76,
  },
  {
    id: 'troy',
    name: 'Troy',
    slug: 'troy',
    abbreviation: 'TROY',
    conference: 'Sun Belt',
    programTier: 'mid-major',
    primaryColor: '#8B0000',
    seed: 13,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 111.8, adjDE: 106.2, adjEM: 5.6, tempo: 70.8, threePointRate: 0.41, threePointPct: 0.354, efgPct: 0.518, ftRate: 0.28, ftPct: 0.734, turnoverRate: 15.8, turnoverForcedRate: 14.6, offReboundRate: 27.4, defReboundRate: 67.8, sosRank: 214, luckFactor: 0.038, kenpomRank: 142 },
    recentForm: { last5wins: 4, last10wins: 8, streakType: 'W', streakLength: 5, avgMarginLast5: 9.2 },
    titleProfileScore: 16,
    upsetVulnerability: 82,
  },
  {
    id: 'chattanooga',
    name: 'Chattanooga',
    slug: 'chattanooga',
    abbreviation: 'CHAT',
    conference: 'SoCon',
    programTier: 'mid-major',
    primaryColor: '#00386B',
    seed: 15,
    region: 'Midwest',
    isFirstFour: false,
    stats: { adjOE: 108.4, adjDE: 108.2, adjEM: 0.2, tempo: 71.4, threePointRate: 0.44, threePointPct: 0.348, efgPct: 0.504, ftRate: 0.30, ftPct: 0.738, turnoverRate: 16.8, turnoverForcedRate: 14.2, offReboundRate: 29.8, defReboundRate: 65.8, sosRank: 278, luckFactor: 0.064, kenpomRank: 256 },
    recentForm: { last5wins: 4, last10wins: 7, streakType: 'W', streakLength: 3, avgMarginLast5: 5.8 },
    titleProfileScore: 5,
    upsetVulnerability: 93,
  },
  // First Four 14 seed
  {
    id: 'lipscomb-midwest',
    name: 'Lipscomb',
    slug: 'lipscomb-midwest',
    abbreviation: 'LIP',
    conference: 'ASUN',
    programTier: 'mid-major',
    primaryColor: '#4B2E84',
    seed: 14,
    region: 'Midwest',
    isFirstFour: true,
    stats: { adjOE: 109.8, adjDE: 107.2, adjEM: 2.6, tempo: 72.4, threePointRate: 0.46, threePointPct: 0.352, efgPct: 0.508, ftRate: 0.30, ftPct: 0.738, turnoverRate: 17.2, turnoverForcedRate: 14.4, offReboundRate: 28.4, defReboundRate: 66.4, sosRank: 232, luckFactor: 0.048, kenpomRank: 174 },
    recentForm: { last5wins: 3, last10wins: 6, streakType: 'W', streakLength: 2, avgMarginLast5: 4.8 },
    titleProfileScore: 10,
    upsetVulnerability: 88,
  },
  {
    id: 'umbc',
    name: 'UMBC',
    slug: 'umbc',
    abbreviation: 'UMBC',
    conference: 'America East',
    programTier: 'low-major',
    primaryColor: '#FFC20E',
    seed: 16,
    region: 'Midwest',
    isFirstFour: true,
    stats: { adjOE: 107.6, adjDE: 109.2, adjEM: -1.7, tempo: 67.6, threePointRate: 0.36, threePointPct: 0.359, efgPct: 0.492, ftRate: 0.32, ftPct: 0.720, turnoverRate: 17.9, turnoverForcedRate: 19.0, offReboundRate: 35.1, defReboundRate: 79.4, sosRank: 320, luckFactor: 0.000, kenpomRank: 290 },
    recentForm: { last5wins: 2, last10wins: 5, streakType: 'W', streakLength: 1, avgMarginLast5: -1.3 },
    titleProfileScore: 3,
    upsetVulnerability: 96,
    espnId: 2427,
  },
  {
    id: 'howard',
    name: 'Howard',
    slug: 'howard',
    abbreviation: 'HOW',
    conference: 'MEAC',
    programTier: 'low-major',
    primaryColor: '#003A63',
    seed: 16,
    region: 'Midwest',
    isFirstFour: true,
    stats: { adjOE: 103.5, adjDE: 106.2, adjEM: -2.8, tempo: 67.2, threePointRate: 0.36, threePointPct: 0.347, efgPct: 0.474, ftRate: 0.32, ftPct: 0.720, turnoverRate: 16.9, turnoverForcedRate: 19.0, offReboundRate: 32.0, defReboundRate: 81.6, sosRank: 295, luckFactor: 0.000, kenpomRank: 300 },
    recentForm: { last5wins: 2, last10wins: 4, streakType: 'L', streakLength: 1, avgMarginLast5: -5.2 },
    titleProfileScore: 2,
    upsetVulnerability: 97,
    espnId: 2249,
  },
]

// ─── 2026 Real Data ────────────────────────────────────────────────────────────
// All pages import from mockData for convenience; we forward to realData so
// every route automatically uses the live 2026 bracket instead of 2025 mocks.

export { ALL_TEAMS, TEAMS_BY_REGION } from '@/lib/realData'
import { ALL_TEAMS } from '@/lib/realData'

export const TEAMS_BY_SLUG = new Map(ALL_TEAMS.map(t => [t.slug, t]))
export const TEAMS_BY_ID = new Map(ALL_TEAMS.map(t => [t.id, t]))

export function getTeamsByRegion(region: MockTeam['region']): MockTeam[] {
  return ALL_TEAMS.filter(t => t.region === region).sort((a, b) => a.seed - b.seed)
}

export function getTopContenders(n = 8): MockTeam[] {
  return [...ALL_TEAMS]
    .filter(t => !t.isFirstFour)
    .sort((a, b) => b.titleProfileScore - a.titleProfileScore)
    .slice(0, n)
}

export function getTopUpsetAlerts(n = 5): Array<{ team: MockTeam; opponent: MockTeam | null }> {
  return ALL_TEAMS
    .filter(t => !t.isFirstFour && t.seed <= 12 && t.seed >= 5)
    .sort((a, b) => b.upsetVulnerability - a.upsetVulnerability)
    .slice(0, n)
    .map(team => ({ team, opponent: null }))
}
